
networks:
  tasksense_net:

services:
  postgres:
    image: postgres:16
    container_name: task_postgres
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - tasksense_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:9
    container_name: task_flyway
    command: >
      -url=jdbc:postgresql://postgres:5432/taskdb
      -user=postgres
      -password=postgres
      -connectRetries=60
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tasksense_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: task_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - tasksense_net
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: task_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tasksense_net
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
