package dev.alro127.tasksense.domain.enums;

public enum NotificationType {
    TASK_ASSIGNED,
    WORKSPACE_INVITE,
    WORKSPACE_INVITE_ACCEPT,
    WORKSPACE_JOIN_REQUEST,
    WORKSPACE_REVIEW_REQUEST,
    WORKSPACE_REMOVE_MEMBER,
    WORKSPACE_ROLE_CHANGE,
    PROJECT_JOIN_REQUEST,
    COMMENT_MENTION,
    TASK_REMINDER, PROJECT_ROLE_UPDATED
}