package dev.alro127.tasksense.domain.enums;

public enum NotificationType {
    // WORKSPACE
    WORKSPACE_INVITE,
    WORKSPACE_INVITE_ACCEPT,
    WORKSPACE_JOIN_REQUEST,
    WORKSPACE_REVIEW_REQUEST,
    WORKSPACE_REMOVE_MEMBER,
    WORKSPACE_ROLE_CHANGE,
    WORKSPACE_LEAVE,

    // PROJECT
    PROJECT_JOIN_REQUEST,
    PROJECT_REVIEW_REQUEST,
    PROJECT_ADD_MEMBER,
    PROJECT_REMOVE_MEMBER,
    PROJECT_ROLE_CHANGE,
    PROJECT_LEAVE,

    // TASK
    TASK_ASSIGNED,
    TASK_REMINDER,

    // COMMENT
    COMMENT_MENTION,
    COMMENT_REACTION,
    COMMENT_TASK,
    TASK_UNASSIGNED,
    WORKFLOW_UPDATED,

    // WORKFLOW
    WORKFLOW_RATED,
    WORKFLOW_FAVORITED,
    WORKFLOW_COMMENT,
    WORKFLOW_COMMENT_MENTION,
    WORKFLOW_COMMENT_REACTION,
    WORKFLOW_USED,
    }