package dev.alro127.tasksense.domain.enums;

public enum NotificationType {
    // WORKSPACE
    WORKSPACE_INVITE,
    WORKSPACE_INVITE_ACCEPT,
    WORKSPACE_JOIN_REQUEST,
    WORKSPACE_REVIEW_REQUEST,
    WORKSPACE_REMOVE_MEMBER,
    WORKSPACE_ROLE_CHANGE,

    // PROJECT
    PROJECT_JOIN_REQUEST,
    PROJECT_ROLE_UPDATED,

    // TASK
    TASK_ASSIGNED,
    TASK_REMINDER,
    // COMMENT
    COMMENT_MENTION,
    COMMENT_REACTION,
    COMMENT_TASK,

}